### ISSUE TITLE
使用阿里云C2时，报错websocket: bad status

### ISSUE THREAD

**Issue by shadow1ng** [uknowsec/frpModify#5]
使用阿里云CDN时，报错`[W] [service.go:103] login to server failed: websocket.Dial ws://61.240.227.243:80/websocket: bad status`
frps端配置:
![image](https://user-images.githubusercontent.com/39651966/105572698-b862f200-5d93-11eb-8f1f-f83f2ec50e5d.png)

frpc端配置:
![image](https://user-images.githubusercontent.com/39651966/105572710-d16ba300-5d93-11eb-9a80-36a10cbef855.png)

无法连接，尝试把server_addr 改为cdn_ip也是同样的报错。

cdn连通性证明:
![image](https://user-images.githubusercontent.com/39651966/105572740-02e46e80-5d94-11eb-88ed-a7210b7e3847.png)

且使用nc 可以接受到数据:
![image](https://user-images.githubusercontent.com/39651966/105572765-260f1e00-5d94-11eb-92a2-3416609d2abd.png)

看起来是因为阿里云cdn把下面两个websocket的需要的header吞掉了
```
Upgrade: websocket
Connection: Upgrade
```
有什么解决办法嘛？师傅测试时用的什么厂商的cdn？

### 另外
我根据你的文章修改时，把验证Upgrade、Connection去掉后，还是会报错，但IP直连是可以的
下图看起来阿里云CDN好像不直接支持websocket?
frps端：
![image](https://user-images.githubusercontent.com/39651966/105572920-02000c80-5d95-11eb-90d1-6e417f84b540.png)

frpc端:
![image](https://user-images.githubusercontent.com/39651966/105572967-35db3200-5d95-11eb-9445-514ab8b692f8.png)
![image](https://user-images.githubusercontent.com/39651966/105572973-3ffd3080-5d95-11eb-84df-3f5546255794.png)

wireshark抓包记录
![image](https://user-images.githubusercontent.com/39651966/105572891-d54bf500-5d94-11eb-912c-52a0c0629f9f.png)

师傅是怎么用cdn保持websocket连接的？

**Comment by uknowsec** [comment]
> 使用阿里云CDN时，报错`[W] [service.go:103] login to server failed: websocket.Dial ws://61.240.227.243:80/websocket: bad status`
> frps端配置:
> ![image](https://user-images.githubusercontent.com/39651966/105572698-b862f200-5d93-11eb-8f1f-f83f2ec50e5d.png)
> 
> frpc端配置:
> ![image](https://user-images.githubusercontent.com/39651966/105572710-d16ba300-5d93-11eb-9a80-36a10cbef855.png)
> 
> 无法连接，尝试把server_addr 改为cdn_ip也是同样的报错。
> 
> cdn连通性证明:
> ![image](https://user-images.githubusercontent.com/39651966/105572740-02e46e80-5d94-11eb-88ed-a7210b7e3847.png)
> 
> 且使用nc 可以接受到数据:
> ![image](https://user-images.githubusercontent.com/39651966/105572765-260f1e00-5d94-11eb-92a2-3416609d2abd.png)
> 
> 看起来是因为阿里云cdn把下面两个websocket的需要的header吞掉了
> 
> ```
> Upgrade: websocket
> Connection: Upgrade
> ```
> 
> 有什么解决办法嘛？师傅测试时用的什么厂商的cdn？
> 
> ### 另外
> 我根据你的文章修改时，把验证Upgrade、Connection去掉后，还是会报错，但IP直连是可以的
> 下图看起来阿里云CDN好像不直接支持websocket?
> frps端：
> ![image](https://user-images.githubusercontent.com/39651966/105572920-02000c80-5d95-11eb-90d1-6e417f84b540.png)
> 
> frpc端:
> ![image](https://user-images.githubusercontent.com/39651966/105572967-35db3200-5d95-11eb-9445-514ab8b692f8.png)
> ![image](https://user-images.githubusercontent.com/39651966/105572973-3ffd3080-5d95-11eb-84df-3f5546255794.png)
> 
> wireshark抓包记录
> ![image](https://user-images.githubusercontent.com/39651966/105572891-d54bf500-5d94-11eb-912c-52a0c0629f9f.png)
> 
> 师傅是怎么用cdn保持websocket连接的？

我测试用的就是阿里云，阿里云配置的时候回源设置为http。另外阿里云是支持websocket的。
https://dcdn.console.aliyun.com/

**Comment by shadow1ng** [comment]
后面解决了，更换腾讯云就正常了，当时咨询阿里云客服，说是新用户不支持websocket

**Comment by kankankankankankan** [comment]
哈喽 我是也遇到此问题，但必须要将frps的配置改为`bind_port = 80`才可以，如果是7000，frpc

```
[common]
server_addr = remote.abc.com.cdn.dnsv1.com #CNAME
server_port = 80
token = uknowsec
protocol = websocket
tls_enable = true
websocket_domain = remote.abc.com #为加速域名

[RDP]
local_ip = 127.0.0.1
remote_port = 7011
local_port = 3389
```

运行后出现
```
frp to support Domain fronting
Modified by Uknow
2021/05/29 15:51:43 [W] [service.go:103] login to server failed: websocket.Dial
ws://remote.abc.com.cdn.dnsv1.com:80/websocket: read tcp 192.168.110.200:57
183->139.170.157.216:80: wsarecv: An existing connection was forcibly closed by
the remote host.
websocket.Dial ws://remote.abc.com.cdn.dnsv1.com:80/websocket: read tcp 192
.168.110.200:57183->139.170.157.216:80: wsarecv: An existing connection was forc
ibly closed by the remote host.
```

抓包结果
```
GET /websocket HTTP/1.1
Host: remote.abc.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: OFsM29YFP+n2vlaxWBcqWA==
Origin: http://remote.abc.com.cdn.dnsv1.com:80
Sec-WebSocket-Version: 13

```


不知道如何解决,感谢！
